### PR TITLE
Upgrade to husky@5

### PR DESCRIPTION
**Pull request by perrin4869**
Just upgraded in `services-typescript` so might as well upgrade everywhere else XD

https://dev.to/typicode/what-s-new-in-husky-5-32g5

### CODE REVIEW

**Comment by laxa88** [comment]
just wondering, what's pinst for?

**Review by laxa88 — APPROVED** [review]

**Comment by phieronymus** [comment]
@laxa88 It is used in the package.json to control whether the hooks are enabled or not on certain commands 🙂 

```
    "prepublishOnly": "pinst --disable",
    "postpublish": "pinst --enable"
```

**Comment by laxa88** [comment]
@phieronymus i know what it does, but ... i don't understand why we're using it? 🙇

**Comment by perrin4869** [comment]
Took it straight from the documentation. It makes sure that when you install this module as a dependency, husky install isn't run

**Pull request merged**
