### PR TITLE
Fix ec language types

### PR DESCRIPTION
**Pull request by phieronymus**
Used in the following type:

```
customFieldsTitles?: Partial<Record<Languages, string>> | null;
orderSummaryTitles?: Partial<Record<Languages, string>> | null;
customFields?: Partial<Record<Languages, ECFormCustomField[]>> | null;
```

The keys for those items are camelized on the SDK and snakified when formatting for the API. When using them the proper type is the camelized version as we want to use the front-end-formatted version. Please feel free to tell me if I overlook anything.

### CODE REVIEW

**Comment by perrin4869** [comment]
Well... I'm using the values of these guys in [here](https://github.com/univapaycast/services-typescript/blob/af6500df9bea7ea82012cd55a2398bc6e1e789bb/services/checkout/src/schemas/common.ts#L52)
This is a case where I'm not sure camelizing is the way to go? I'd vote to keep them always snake case...

**Comment by phieronymus** [comment]
The current type is wrong though 🤔 I can ignore those properties in the camelization process but it would make the code more complexe and be breaking. Should we get that as a quick fix and maybe change that for next time we want a breaking version?

**Comment by phieronymus** [comment]
The thing is that we do not have much gain with having this inconsistency 🤔

**Review by perrin4869 — APPROVED** [review]
Nice!!! Thanks for this!!!

**Pull request merged**
