### PR TITLE
Add IssuerUrl resource

### PR DESCRIPTION
**Pull request by perrin4869**
Missing tests yet

### CODE REVIEW

**Comment by phieronymus** [comment]
Looking good. However you may want this route to be in the same file as the other charges route as the resource belongs to them 🙂

**Comment by phieronymus** [comment]
Adding me and @laxa88 to the list of reviewers for this Pull Request 🙂

**Comment by perrin4869** [comment]
OK, moved to the `charges` route. BTW, not sure about the response format. Tried to guess based on Kingston's hints!

**Comment by perrin4869** [comment]
Good question! No idea lol
In Slack @kgston said that the response format is

```scala
implicit val format: OFormat[OnlineData] = (
    (__ \ "issuer_token").formatOption[String] ~
      (__ \ "http_method").formatOption[String]
  )(OnlineData.apply, unlift(OnlineData.unapply))
```

Which I just assumed means it gets an `httpMethod` property, but maybe I just can't read this format thing.
BTW, I also marked the returned properties `storeId` and `chargeId`, but I notice now that maybe they aren't being set afterall

**Comment by kgston** [comment]
The `http_method` tells you which http verb to use when making the request to the `issuer_token` which contains the URL you need to call. It can be `GET`, but sometimes it can be `PUT` or `POST`.

**Comment by perrin4869** [comment]
Went ahead and added `TransactionTokenOnlineData` inside this PR too

**Comment by phieronymus** [comment]
Merging this. Thanks for the update!

**Pull request merged**
