### PR TITLE
Update ECForms types to allow null values

### PR DESCRIPTION
**Pull request by perrin4869**
hm... something like this? Optional fields are kinda hard to handle on my end, nullable fields are easier!

### CODE REVIEW

**Comment by perrin4869** [comment]
hm... depends what `ECForm` will be used for I guess - if it's for `POST` operations, optional fields are cool

**Comment by perrin4869** [comment]
Had a change of heart and returned the `?` to the fields - you can still send me `POST` and `PATCH` forms without those fields, but I'll default them all to null - they will be present in all `GET` requests

**Comment by perrin4869** [comment]
Guess the whole point here is that the fields are nullable lol

**Comment by phieronymus** [comment]
We may think of splitting the types at one point for query and mutation. For now I believe this is good for the current usecase and do a big refactoring seems ta bit out of the scope of this PR.

Let me merge this 🙂 Also thanks for adding the pendingRedirectURL

**Review by phieronymus — APPROVED** [review]

**Pull request merged**
